name: Build and Release with Notes

on:
  push:
    branches:
      - main

jobs:
  build-and-release:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Build Docker image
        run: |
          docker build -t pyinstaller .

      - name: Run Docker container
        run: |
          docker run \
              -v .:/work \
              --workdir /work \
              pyinstaller \
              "/work/build.sh"

      - name: Create or update release
        uses: ncipollo/release-action@v1
        with:
          allowUpdates: true
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: latest
          bodyFile: ./build/version.txt
          artifacts: "./build/dist/glances"
